### ISSUE TITLE
duplicate symbols found error on macosx

### ISSUE THREAD

**Issue by samarism** [aerospike/client-lua#1]
Hi,

When running the ./build_osx.sh i get many such errors:
"
duplicate symbol _luaV_lessthan in:
    /usr/local/lib/libaerospike.a(lvm.o)
    /usr/local/lib/liblua.a(lvm.o)
....
"

i installed lua on my macosx as per the instructions given here: https://www.aerospike.com/docs/client/c/install/macosx.html

Any ideas how this can be resolved?

Thanks

**Comment by psi-mankoski** [comment]
As of the Aerospike C Client 3.0.96 (30 Jan. 2015), the Lua engine is included in the pre-built C client library. We are updating the C client installation instructions to reflect this. In the mean time, the only thing you should need to do is remove "-llua" from the link command lines in your application makefiles or build scripts when linking against the Aerospike C Client library.

**Comment by helipilot50** [comment]
I just made a fix to the build scripts

**Comment by samarism** [comment]
Psi / Hellpilot, Thanks for the fix.
