### ISSUE TITLE
mem_count.h: No such file or directory

### ISSUE THREAD

**Issue by shadylabs** [aerospike/client-lua#2]
Ubuntu 14.04 64bit build_linux.sh  terminated with Error message:

"In file included from /usr/include/aerospike/as_util.h:22:0,
                 from /usr/include/aerospike/as_bytes.h:20,
                 from /usr/include/aerospike/as_key.h:19,
                 from /usr/include/aerospike/aerospike_key.h:33,
                 from src/as_lua.c:13:
/usr/include/citrusleaf/alloc.h:28:23: fatal error: mem_count.h: No such file or directory
 #include "mem_count.h"
                       ^
compilation terminated.
gcc: error: ./src/as_lua.o: No such file or directory "

Any ideas or help?
Thanks
Plamen.

**Comment by psi-mankoski** [comment]
Hello. The "-DMEM_COUNT" in "build_linux.sh" is unnecessary and will lead to this error. We'll fix it. Thanks for the report!

**Comment by psi-mankoski** [comment]
Fixed. Please re-pull and try again. Thanks!
