### ISSUE TITLE
Ubuntu 12.04 LTS /usr/lib/libaerospike.so: undefined symbol: RAND_seed

### ISSUE THREAD

**Issue by contrapunctus-xv** [aerospike/client-lua#3]
I am able run make test successfully on the C client however running the test on lua client gives me the following error
    /usr/lib/libaerospike.so: undefined symbol: RAND_seed

I was able to run the lua client in centOS (vagrant box aerospike/centos-6.5) but not on ubuntu 12.04 LTS (vagrant box ubuntu/precise6)

**Comment by pipe-lord** [comment]
I got it to work if you install libssl0.9.8 only and don't install libssl as what the ubuntu c client instructions say and symlink 

    sudo apt-get install libssl0.9.8
    sudo ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.0.9.8 /usr/lib/x86_64-linux-gnu/libcrypto.so

I'm too new to linux and C to know why this is the case.
