### ISSUE TITLE
Having issue getting value from client

### ISSUE THREAD

**Issue by rcritt** [aerospike/client-lua#6]
I am running this on a Mac OS X computer, Yosemite 10.10.4.

The lua that installs with brew "brew install lua" does not compile.  However I was able to compile by using Lua5.1 and adding changing the src/as_lua.c headers have the following.
With this change I was able to compile as_lua.so.

> # include <lua-5.1/lua.h>
> # include <lua-5.1/lauxlib.h>
> # include <lua-5.1/lualib.h>

After that I tried accessing a database that I have accessed using the NodeJS driver.  The object I access has a bin entry that contains a hash with string as the key, number as the value.  So the bin entries are not string or numeric values, but table entries in themselves.
In NodeJS the result looks something like the following.

> {"objectId":"12345699","bins":{"amap":{"key1":330,"key2":44,"key3":99}}}

In Lua5.1 I am able to connect & disconnect to the cluster successfully.
However if I run the following...

> /usr/local/Cellar/lua51/5.1.5/bin/lua-5.1 main_testing.lua

I get this result.

> ## connected ##   0
> lua-5.1(86899,0x7fff7301d300) malloc: **\* error for object 0x1032232c8: pointer being freed was not allocated
> **\* set a breakpoint in malloc_error_break to debug
> [1]    86899 abort      /usr/local/Cellar/lua51/5.1.5/bin/lua-5.1 main_testing.lua

If I run this in Luajit I get a segmentation fault.

Is there some way around this?  In particular I was hoping to run this sort of thing in OpenResty, which uses Luajit.

Thank you for creating this project.

**Comment by helipilot50** [comment]
Hello,

It looks like the Bin that you wrote using Node is storing the Aerospike type of Map. This example Lua client code only implements the Bin types of Integer, String and List, and does not implement the Map type. I'm guessing that you are falling out of the poorly coded case statement (by me :)  near line 240.

If you want to try and implement this your self, take a look at as_lua.c. to Implement the 'put' add code near line 54, and to implement the get, add code near line 218.
